// Scheduled blog post content — loaded from src/scheduled/*.md files
// Generated by scripts/gen-all-posts.cjs
// To regenerate: node scripts/gen-all-posts.cjs

const mdFiles = import.meta.glob('../scheduled/*.md', { query: '?raw', import: 'default', eager: true });

export const scheduledContent: Record<string, string> = {};

for (const [path, content] of Object.entries(mdFiles)) {
  const slug = path.split('/').pop()!.replace('.md', '');
  scheduledContent[slug] = content as string;
}
